"""LLM operations for the overnight PCB-engine corpus runner.

Two operations, both designed so mid-tier (Llama-70B class) models succeed:
rigid prompts, structured JSON outputs, forgiving parsing, and exactly one
repair retry per operation.

- nl_to_input_spec():     marketing text -> CircuitSpec (JSON circuit spec)
- review_exceptions():    structured DesignExceptions -> candidate choices
- external_agent_review(): same review, framed as a third-party API consumer
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Optional

from pydantic import ValidationError

from llm import config
from llm.openrouter_client import complete
from schemas.circuit_spec import CircuitSpec

_REPO_ROOT = Path(__file__).resolve().parent.parent


class SpecParseError(Exception):
    """Spec generation failed after the repair retry. Carries the stage dicts
    (token/cost accounting for both attempts) as ``.stages``."""

    def __init__(self, message: str, stages: list[dict]):
        super().__init__(message)
        self.stages = stages


# --------------------------------------------------------------------------
# Prompt construction
# --------------------------------------------------------------------------

_SCHEMA_JSON = json.dumps(CircuitSpec.model_json_schema(), separators=(",", ":"))

SPEC_SCHEMA_PROMPT = (
    "You are a circuit design engineer. You convert a product description into a "
    "JSON circuit specification (CircuitSpec) for an automated PCB generation engine.\n"
    "\n"
    "The output MUST be a single JSON object conforming to this JSON Schema:\n"
    f"{_SCHEMA_JSON}\n"
    "\n"
    "Design rules:\n"
    "1. Every part MUST have \"footprint\" in the exact format \"Library:Name\", "
    "e.g. \"Resistor_SMD:R_0603_1608Metric\".\n"
    "2. Power and ground nets MUST use standard names (VCC, VDD, +3V3, +5V, VBUS, "
    "VIN, VBAT, GND, VSS) and set \"power\": true.\n"
    "3. Decoupling capacitors MUST use value \"100nF\" (never \"0.1uF\" or \"104\"). "
    "Add one 100nF cap per IC power pin, connected between the power net and GND, "
    "plus a 10uF bulk capacitor on the power input.\n"
    "4. For well-known KiCad library parts set \"lib\" and \"part\" (common symbol "
    "libraries: Device, Connector_Generic, Connector_USB, MCU_Microchip_SAMD, "
    "MCU_Nordic_nRF, MCU_Espressif_ESP32, MCU_RaspberryPi_RP2xxx, Regulator_Linear, "
    "Sensor_Temperature, Sensor_Pressure, Sensor_Motion, Sensor_Optical, "
    "Interface_USB, Memory_Flash, Battery_Management, LED, Switch). Net endpoints "
    "must then use real pin names/numbers from that symbol.\n"
    "5. For unfamiliar or complex ICs, define a CUSTOM part instead: set \"lib\": null "
    "and give explicit \"pins\" (num, name, func). func is one of: power_in, "
    "power_out, input, output, bidirectional, tristate, passive, unspecified, "
    "no_connect. This avoids pin-name mismatches — when in doubt, use a custom part.\n"
    "6. Common footprint libraries: Resistor_SMD, Capacitor_SMD, Inductor_SMD, "
    "Package_QFP, Package_SO, Package_TO_SOT_SMD, Package_DFN_QFN, "
    "Connector_PinHeader_2.54mm, Connector_USB, Crystal, LED_SMD, Button_Switch_SMD, "
    "Diode_SMD. Package_LGA does NOT exist — use Package_DFN_QFN instead.\n"
    "7. Net \"pins\" entries are \"REF.PIN\" strings, where PIN is a pin number or pin "
    "name, e.g. \"U1.VDD\", \"C1.1\".\n"
    "8. Use generic Part Device:R / Device:C for passives. Use reference designator "
    "prefixes: U (ICs), C (caps), R (resistors), J (connectors), Y (crystals), "
    "D (diodes/LEDs), SW (switches).\n"
    "9. Group parts into functional blocks with the \"group\" field "
    "(5-15 parts per group).\n"
    "\n"
    "STRICT OUTPUT REQUIREMENT: Output ONLY the JSON object. No markdown fences. "
    "No commentary. No text before or after the JSON."
)

# Worked examples generated by the corpus pipeline (built in parallel); loaded
# at call time so they are picked up as soon as they exist.
WORKED_EXAMPLE_PATHS = [
    "corpus/specs/ads1115-adc.json",
    "corpus/specs/feather-rp2040.json",
]

# Hand-written fallback example: simple I2C sensor breakout, 4 parts.
_INLINE_EXAMPLE: dict = {
    "schema_version": "1",
    "board": {"name": "i2c-temp-breakout", "outline_hint_mm": [25.4, 17.8], "layers": 2},
    "parts": [
        {
            "ref": "U1",
            "lib": None,
            "part": None,
            "value": "TMP102",
            "footprint": "Package_TO_SOT_SMD:SOT-563",
            "pins": [
                {"num": "1", "name": "SCL", "func": "input"},
                {"num": "2", "name": "GND", "func": "power_in"},
                {"num": "3", "name": "ALERT", "func": "output"},
                {"num": "4", "name": "ADD0", "func": "input"},
                {"num": "5", "name": "VCC", "func": "power_in"},
                {"num": "6", "name": "SDA", "func": "bidirectional"},
            ],
            "group": "sensor",
        },
        {
            "ref": "C1",
            "lib": "Device",
            "part": "C",
            "value": "100nF",
            "footprint": "Capacitor_SMD:C_0603_1608Metric",
            "group": "sensor",
        },
        {
            "ref": "R1",
            "lib": "Device",
            "part": "R",
            "value": "10K",
            "footprint": "Resistor_SMD:R_0603_1608Metric",
            "group": "sensor",
        },
        {
            "ref": "J1",
            "lib": "Connector_Generic",
            "part": "Conn_01x04",
            "footprint": "Connector_PinHeader_2.54mm:PinHeader_1x04_P2.54mm_Vertical",
            "group": "io",
        },
    ],
    "nets": [
        {"name": "VCC", "power": True, "pins": ["U1.VCC", "C1.1", "R1.1", "J1.1"]},
        {"name": "GND", "power": True, "pins": ["U1.GND", "U1.ADD0", "C1.2", "J1.2"]},
        {"name": "SDA", "pins": ["U1.SDA", "J1.3"]},
        {"name": "SCL", "pins": ["U1.SCL", "J1.4"]},
        {"name": "ALERT", "stub": True, "pins": ["U1.ALERT", "R1.2"]},
    ],
}


def _load_worked_examples() -> list[dict]:
    examples = []
    for rel in WORKED_EXAMPLE_PATHS:
        path = _REPO_ROOT / rel
        if path.is_file():
            try:
                examples.append(json.loads(path.read_text()))
            except (OSError, ValueError):
                continue
    return examples or [_INLINE_EXAMPLE]


# --------------------------------------------------------------------------
# Forgiving JSON extraction
# --------------------------------------------------------------------------

def _strip_fences(text: str) -> str:
    """Strip markdown code fences and surrounding noise from model output."""
    t = text.strip()
    if t.startswith("```"):
        first_nl = t.find("\n")
        t = t[first_nl + 1 :] if first_nl != -1 else ""
        t = t.strip()
    if t.endswith("```"):
        t = t[:-3].strip()
    return t


def _loads_forgiving(text: str, opener: str = "{", closer: str = "}") -> Any:
    """json.loads with fence stripping; falls back to the outermost
    opener...closer slice if there is surrounding commentary."""
    t = _strip_fences(text)
    try:
        return json.loads(t)
    except ValueError:
        start, end = t.find(opener), t.rfind(closer)
        if start == -1 or end <= start:
            raise
        return json.loads(t[start : end + 1])


def _stage_dict(stage: str, resp) -> dict:
    return {
        "stage": stage,
        "model": resp.model,
        "tokens_in": resp.tokens_in,
        "tokens_out": resp.tokens_out,
        "latency_s": resp.latency_s,
        "cost_usd": resp.cost_usd,
    }


# --------------------------------------------------------------------------
# Operation 1: marketing text -> CircuitSpec
# --------------------------------------------------------------------------

async def nl_to_input_spec(
    marketing_text: str,
    board_id: str,
    model: Optional[str] = None,
    spend_tracker: Any = None,
    client: Any = None,
) -> tuple[CircuitSpec, list[dict]]:
    """Turn marketing text into a validated CircuitSpec.

    Returns (spec, stage_dicts). One completion plus at most one repair call;
    raises SpecParseError (carrying all stage dicts) if both fail.
    """
    model = model or config.DESIGN_MODEL
    examples = _load_worked_examples()
    examples_block = "\n\n".join(
        f"Worked example {i + 1} (a complete valid CircuitSpec):\n"
        + json.dumps(ex, separators=(",", ":"))
        for i, ex in enumerate(examples)
    )
    messages = [
        {"role": "system", "content": SPEC_SCHEMA_PROMPT + "\n\n" + examples_block},
        {
            "role": "user",
            "content": (
                f"Board id: {board_id}\n\n"
                f"Marketing description:\n{marketing_text}\n\n"
                "Produce the complete CircuitSpec JSON object for this board now. "
                "Include every IC, connector, passive, and decoupling capacitor. "
                "JSON object only."
            ),
        },
    ]

    stages: list[dict] = []

    async def _attempt(msgs: list[dict]):
        resp = await complete(
            msgs,
            model,
            response_format={"type": "json_object"},
            spend_tracker=spend_tracker,
            client=client,
        )
        stages.append(_stage_dict("design_nl_to_input", resp))
        return resp

    resp = await _attempt(messages)
    try:
        return CircuitSpec.model_validate(_loads_forgiving(resp.text)), stages
    except (ValueError, ValidationError) as err:
        error_text = str(err)

    repair_messages = messages + [
        {"role": "assistant", "content": resp.text},
        {
            "role": "user",
            "content": (
                f"Your previous output failed validation with this error:\n{error_text}\n\n"
                "Return the corrected complete JSON object only."
            ),
        },
    ]
    resp2 = await _attempt(repair_messages)
    try:
        return CircuitSpec.model_validate(_loads_forgiving(resp2.text)), stages
    except (ValueError, ValidationError) as err2:
        raise SpecParseError(
            f"spec generation failed for {board_id!r} after repair retry: {err2}",
            stages=stages,
        ) from err2


# --------------------------------------------------------------------------
# Operation 2: exception review -> candidate choices
# --------------------------------------------------------------------------

_INTERNAL_REVIEW_SYSTEM = (
    "You are reviewing structured PCB design exceptions raised by an automated "
    "board-generation engine. Each exception lists machine-applicable correction "
    "candidates. For EACH exception, pick exactly ONE candidate by id. Prefer the "
    "cheapest candidate that plausibly fixes the root cause. Do not repeat a "
    "correction listed in the prior-corrections history — it already failed or was "
    "already applied.\n"
    "\n"
    "STRICT OUTPUT REQUIREMENT: Output ONLY a JSON array of objects of the form "
    '{"exception_id": "...", "candidate_id": "..."} — one entry per exception, '
    "no markdown fences, no commentary."
)

_EXTERNAL_REVIEW_SYSTEM = (
    "You are a third-party engineering agent using a PCB generation API. The API "
    "exposes two tools: generate_design(spec) runs the full schematic+layout "
    "pipeline on a JSON circuit spec and returns design exceptions; "
    "apply_correction(exception_id, candidate_id) mutates the spec with the chosen "
    "candidate's action and lets you regenerate. Your last generate_design call "
    "returned the exceptions below; decide which correction candidate to apply for "
    "each exception. Pick exactly ONE candidate id per exception, preferring cheap "
    "fixes that address the root cause, and never repeating a correction from the "
    "prior-corrections history.\n"
    "\n"
    "STRICT OUTPUT REQUIREMENT: Output ONLY a JSON array of objects of the form "
    '{"exception_id": "...", "candidate_id": "..."} — one entry per exception, '
    "no markdown fences, no commentary."
)


def _as_dict(obj: Any) -> dict:
    return obj.model_dump() if hasattr(obj, "model_dump") else dict(obj)


def _render_exceptions(exceptions: list[dict]) -> str:
    lines = []
    for exc in exceptions:
        code = exc.get("code", "")
        sev = exc.get("severity", "")
        head = f"{exc['id']} [{code}]"
        if sev:
            head += f" ({sev})"
        lines.append(f"{head}: {exc.get('message', '')}")
        for cand in exc.get("candidates", []):
            tags = [
                f"{key}={cand[key]}"
                for key in ("action", "cost_hint")
                if cand.get(key)
            ]
            extra = f" ({', '.join(tags)})" if tags else ""
            lines.append(f"  {cand['id']}: {cand.get('human_summary', '')}{extra}")
    return "\n".join(lines)


def _validate_choices(raw: Any, valid: dict[str, set[str]]) -> Optional[list[dict]]:
    """Return normalized choices if raw covers every exception with a valid
    candidate id, else None."""
    if not isinstance(raw, list):
        return None
    picked: dict[str, str] = {}
    for item in raw:
        if not isinstance(item, dict):
            return None
        exc_id = item.get("exception_id")
        cand_id = item.get("candidate_id")
        if exc_id not in valid or cand_id not in valid[exc_id]:
            return None
        picked[exc_id] = cand_id
    if set(picked) != set(valid):
        return None
    return [{"exception_id": e, "candidate_id": picked[e]} for e in valid]


async def _review(
    exceptions: list[dict],
    board_context: dict,
    history: list[str],
    system_prompt: str,
    stage: str,
    model: Optional[str],
    spend_tracker: Any,
    client: Any,
) -> tuple[list[dict], list[dict], bool]:
    model = model or config.REVIEW_MODEL
    exceptions = [_as_dict(e) for e in exceptions]
    valid = {
        e["id"]: {c["id"] for c in e.get("candidates", [])} for e in exceptions
    }

    context_block = json.dumps(board_context, separators=(",", ":"), default=str)
    history_block = (
        "Prior corrections already applied this run (do NOT repeat these):\n"
        + "\n".join(f"- {h}" for h in history)
        if history
        else "No prior corrections this run."
    )
    messages = [
        {"role": "system", "content": system_prompt},
        {
            "role": "user",
            "content": (
                f"Board context:\n{context_block}\n\n"
                f"{history_block}\n\n"
                f"Design exceptions and their correction candidates:\n"
                f"{_render_exceptions(exceptions)}\n\n"
                "Pick one candidate per exception. JSON array only."
            ),
        },
    ]

    stages: list[dict] = []

    async def _attempt(msgs: list[dict]):
        resp = await complete(
            msgs, model, spend_tracker=spend_tracker, client=client
        )
        stages.append(_stage_dict(stage, resp))
        return resp

    resp = await _attempt(messages)
    try:
        raw = _loads_forgiving(resp.text, opener="[", closer="]")
    except ValueError:
        raw = None
    choices = _validate_choices(raw, valid)
    if choices is not None:
        return choices, stages, False

    valid_listing = "; ".join(
        f"{exc_id}: [{', '.join(sorted(cands))}]" for exc_id, cands in valid.items()
    )
    repair_messages = messages + [
        {"role": "assistant", "content": resp.text},
        {
            "role": "user",
            "content": (
                "Your previous answer was invalid. The only valid ids are — "
                f"{valid_listing}. Return a JSON array with exactly one entry per "
                'exception, each of the form {"exception_id": "...", '
                '"candidate_id": "..."}. JSON array only.'
            ),
        },
    ]
    resp2 = await _attempt(repair_messages)
    try:
        raw2 = _loads_forgiving(resp2.text, opener="[", closer="]")
    except ValueError:
        raw2 = None
    choices = _validate_choices(raw2, valid)
    if choices is not None:
        return choices, stages, False

    # Deterministic fallback: first candidate (c1, the deterministic-policy pick).
    fallback = []
    for e in exceptions:
        cands = e.get("candidates", [])
        fallback.append(
            {
                "exception_id": e["id"],
                "candidate_id": cands[0]["id"] if cands else "c1",
            }
        )
    return fallback, stages, True


async def review_exceptions(
    exceptions: list[dict],
    board_context: dict,
    history: list[str],
    model: Optional[str] = None,
    spend_tracker: Any = None,
    client: Any = None,
    stage: str = "review_internal",
) -> tuple[list[dict], list[dict], bool]:
    """Pick a correction candidate for each exception.

    Returns (choices, stage_dicts, fallback_used). choices is a list of
    {"exception_id", "candidate_id"}; fallback_used is True when both LLM
    attempts were invalid and c1 was picked deterministically for every
    exception.
    """
    return await _review(
        exceptions,
        board_context,
        history,
        system_prompt=_INTERNAL_REVIEW_SYSTEM,
        stage=stage,
        model=model,
        spend_tracker=spend_tracker,
        client=client,
    )


async def external_agent_review(
    exceptions: list[dict],
    board_context: dict,
    history: list[str],
    model: Optional[str] = None,
    spend_tracker: Any = None,
    client: Any = None,
    stage: str = "review_external",
) -> tuple[list[dict], list[dict], bool]:
    """Same contract as review_exceptions, but framed as a third-party agent
    consuming the PCB generation API (generate_design / apply_correction)."""
    return await _review(
        exceptions,
        board_context,
        history,
        system_prompt=_EXTERNAL_REVIEW_SYSTEM,
        stage=stage,
        model=model,
        spend_tracker=spend_tracker,
        client=client,
    )
